### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hbweb** [briisk/http-wrapper#11]
Great works guy. 
Just wonder which doctype do you use to add documentation code like this your source code? Cheers
```
/** 
@param

*/
```

**Comment by dakolech** [comment]
It's just a JSDoc format, but it's working also with TypeScript. You can use https://github.com/TypeStrong/typedoc to generate documentation.

**Comment by hbweb** [comment]
Great, thanks dude @dakolech

**Comment by hbweb** [comment]
@dakolech in your source file you have document comment on all methods for example

```
/**
   * Handler which generate url for all requests. It uses baseUrl if url doesn't start with 'http'' or 'www'.
   * @param url     Url string
   * @returns       Generated url string
   */
```
Did this auto generate from your IDE (vscode) or from Typedocs or you just manually added them ? Sorry for all the questions :)

**Comment by dakolech** [comment]
No problem :) I've added them manually. I don't trust auto generated doc :)

**Comment by hbweb** [comment]
aha I would have thought so as it is very neat on what you guys have done. Thanks for a quick rely.
