### ISSUE TITLE
Question: How would someone modify request

### ISSUE THREAD

**Issue by MaestroJurko** [briisk/http-wrapper#20]
```
this.http.post('warehouses', {}).subscribe((request) => {
   console.log(request);
});
```

Request here is an array, but I cannot use ```.map``` on it. How would I do this - I am new to Angular 4?

**Comment by dakolech** [comment]
Can you show the output from `console.log`?

**Comment by MaestroJurko** [comment]
![screen shot 2017-10-18 at 09 22 46](https://user-images.githubusercontent.com/616192/31687531-fbe39616-b3e5-11e7-8d95-ac170e723374.png)

**Comment by MaestroJurko** [comment]
Actually when I return an object 

```
{
list: [],
total: 100
}
```

and I want to do ```request.list```, it states ```property list does not exist on type '{}'```

**Comment by MaestroJurko** [comment]
I found the issue,

```
this.http.post<ListItems>
```
